"""
PDF Compliance Report Generator
Generates audit-ready PDF reports for PCI DSS v4.0.1 and GDPR compliance.

DevPulse Patent 4 — Automated Compliance Evidence Generation
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ── Color Palette ─────────────────────────────────────────────────────────────
BRAND_PRIMARY = colors.HexColor("#1a1a2e")
BRAND_ACCENT = colors.HexColor("#0f3460")
STATUS_PASS = colors.HexColor("#16a34a")
STATUS_FAIL = colors.HexColor("#dc2626")
STATUS_WARN = colors.HexColor("#eab308")
HEADER_BG = colors.HexColor("#1e293b")
ROW_ALT = colors.HexColor("#f8fafc")
BORDER_COLOR = colors.HexColor("#e2e8f0")
TEXT_MUTED = colors.HexColor("#64748b")


def _build_styles() -> dict[str, ParagraphStyle]:
    """Create reusable paragraph styles for the report."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=22,
            textColor=BRAND_PRIMARY,
            spaceAfter=6,
            alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base["Normal"],
            fontSize=11,
            textColor=TEXT_MUTED,
            alignment=TA_CENTER,
            spaceAfter=20,
        ),
        "section": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontSize=14,
            textColor=BRAND_PRIMARY,
            spaceBefore=16,
            spaceAfter=8,
        ),
        "subsection": ParagraphStyle(
            "SubsectionHeading",
            parent=base["Heading3"],
            fontSize=11,
            textColor=BRAND_ACCENT,
            spaceBefore=10,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "BodyText",
            parent=base["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155"),
        ),
        "small": ParagraphStyle(
            "SmallText",
            parent=base["Normal"],
            fontSize=8,
            leading=11,
            textColor=TEXT_MUTED,
        ),
        "table_header": ParagraphStyle(
            "TableHeader",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.white,
            leading=10,
        ),
        "table_cell": ParagraphStyle(
            "TableCell",
            parent=base["Normal"],
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#334155"),
        ),
    }


def _status_color(status: str) -> colors.Color:
    """Map status string to color."""
    s = status.upper()
    if s == "PASS" or s == "COMPLIANT":
        return STATUS_PASS
    if s == "FAIL" or s == "NON_COMPLIANT":
        return STATUS_FAIL
    return STATUS_WARN


def _status_label(status: str) -> str:
    """Map status to display label."""
    s = status.upper()
    if s == "PASS":
        return "PASS"
    if s == "FAIL":
        return "FAIL"
    if s == "COMPLIANT":
        return "COMPLIANT"
    if s == "NON_COMPLIANT":
        return "NON-COMPLIANT"
    if s == "PARTIAL_COMPLIANCE":
        return "PARTIAL"
    return "WARNING"


def _make_status_badge(status: str) -> Paragraph:
    """Create a colored status badge."""
    label = _status_label(status)
    color = _status_color(status)
    hex_color = f"#{color.hexval()[2:]}" if hasattr(color, "hexval") else "#333"
    return Paragraph(
        f'<font color="{hex_color}"><b>{label}</b></font>',
        ParagraphStyle("Badge", fontSize=8, leading=10),
    )


def _header_footer(canvas, doc):
    """Draw header and footer on each page."""
    canvas.saveState()
    # Header line
    canvas.setStrokeColor(BRAND_PRIMARY)
    canvas.setLineWidth(1.5)
    canvas.line(40, A4[1] - 45, A4[0] - 40, A4[1] - 45)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(
        40, A4[1] - 40, "DevPulse API Security — Compliance Evidence Report"
    )
    canvas.drawRightString(A4[0] - 40, A4[1] - 40, "CONFIDENTIAL")
    # Footer
    canvas.setStrokeColor(BORDER_COLOR)
    canvas.setLineWidth(0.5)
    canvas.line(40, 45, A4[0] - 40, 45)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(40, 32, "Generated by DevPulse API Security Scanner")
    canvas.drawRightString(A4[0] - 40, 32, f"Page {doc.page}")
    canvas.restoreState()


def generate_compliance_pdf(report_data: dict[str, Any]) -> bytes:
    """
    Generate an audit-ready PDF compliance report.

    Args:
        report_data: The structured compliance report dict from
                     compliance.py::generate_compliance_report()

    Returns:
        PDF bytes suitable for HTTP response or file write.
    """
    buf = io.BytesIO()
    styles = _build_styles()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=40,
        rightMargin=40,
        topMargin=55,
        bottomMargin=55,
    )

    elements: list[Any] = []

    # ── Title Page ─────────────────────────────────────────────────────────
    elements.append(Spacer(1, 60))
    elements.append(Paragraph("Compliance Evidence Report", styles["title"]))
    elements.append(
        Paragraph(
            f"PCI DSS v{report_data.get('pci_dss', {}).get('version', '4.0.1')} "
            f"&amp; GDPR (EU 2016/679)",
            styles["subtitle"],
        )
    )
    elements.append(HRFlowable(width="60%", thickness=1, color=BORDER_COLOR))
    elements.append(Spacer(1, 20))

    # Report metadata
    meta = [
        ["Report ID:", report_data.get("report_id", "—")],
        ["Organization:", report_data.get("organization", "—")],
        ["Generated:", report_data.get("generated_at", "—")],
        ["Report Type:", report_data.get("report_type", "both").upper()],
    ]
    meta_table = Table(meta, colWidths=[120, 340])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 9),
                ("FONT", (1, 0), (1, -1), "Helvetica", 9),
                ("TEXTCOLOR", (0, 0), (0, -1), TEXT_MUTED),
                ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#334155")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("ALIGN", (0, 0), (0, -1), "RIGHT"),
            ]
        )
    )
    elements.append(meta_table)
    elements.append(Spacer(1, 30))

    # ── Executive Summary ──────────────────────────────────────────────────
    scan = report_data.get("scan_summary", {})
    pci = report_data.get("pci_dss", {})
    gdpr = report_data.get("gdpr", {})

    elements.append(Paragraph("1. Executive Summary", styles["section"]))

    overall_status = pci.get("overall_status", "UNKNOWN")
    status_color = _status_color(overall_status)
    hex_sc = (
        f"#{status_color.hexval()[2:]}" if hasattr(status_color, "hexval") else "#333"
    )

    elements.append(
        Paragraph(
            f'Overall PCI DSS Status: <font color="{hex_sc}"><b>{_status_label(overall_status)}</b></font>',
            styles["body"],
        )
    )
    elements.append(Paragraph(pci.get("overall_message", ""), styles["body"]))
    elements.append(Spacer(1, 8))

    # Summary table
    summary_data = [
        [
            Paragraph("<b>Metric</b>", styles["table_header"]),
            Paragraph("<b>Value</b>", styles["table_header"]),
        ],
        ["Total Findings", str(scan.get("total_findings", 0))],
        ["Critical", str(scan.get("critical", 0))],
        ["High", str(scan.get("high", 0))],
        ["Medium", str(scan.get("medium", 0))],
        ["Low", str(scan.get("low", 0))],
        ["", ""],
        ["PCI DSS Compliance", f"{pci.get('compliance_percentage', 0)}%"],
        ["Requirements Pass", str(pci.get("requirements_pass", 0))],
        ["Requirements Fail", str(pci.get("requirements_fail", 0))],
        ["Requirements Warn", str(pci.get("requirements_warn", 0))],
        ["", ""],
        ["GDPR Status", _status_label(gdpr.get("overall_status", "UNKNOWN"))],
    ]

    summary_table = Table(summary_data, colWidths=[200, 120])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8),
                ("FONT", (0, 1), (-1, -1), "Helvetica", 8),
                ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
                ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(summary_table)
    elements.append(Spacer(1, 16))

    # ── PCI DSS Requirements Detail ────────────────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("2. PCI DSS v4.0.1 Requirements", styles["section"]))

    reqs = pci.get("requirements", [])
    for req in reqs:
        status = req.get("status", "UNKNOWN")
        sc = _status_color(status)
        hex_s = f"#{sc.hexval()[2:]}" if hasattr(sc, "hexval") else "#333"

        # Requirement header
        elements.append(
            Paragraph(
                f"{req.get('requirement_id', '')} — "
                f"<b>{req.get('title', '')}</b> "
                f'<font color="{hex_s}">[{_status_label(status)}]</font>',
                styles["subsection"],
            )
        )

        elements.append(Paragraph(req.get("description", ""), styles["body"]))
        elements.append(Spacer(1, 4))

        # OWASP category
        elements.append(
            Paragraph(
                f'<font color="#{TEXT_MUTED.hexval()[2:]}">OWASP: {req.get("owasp_category", "")}</font>',
                styles["small"],
            )
        )

        # Evidence
        evidence = req.get("evidence", "")
        if evidence:
            elements.append(Spacer(1, 3))
            elements.append(
                Paragraph(
                    f"<b>Evidence:</b> {evidence}",
                    styles["small"],
                )
            )

        # Findings detail
        findings = req.get("findings", [])
        if findings:
            elements.append(Spacer(1, 3))
            elements.append(Paragraph("<b>Findings:</b>", styles["small"]))
            for f in findings[:5]:
                risk = f.get("risk_level", "medium").upper()
                elements.append(
                    Paragraph(
                        f'• {f.get("issue", "")} <font color="#{TEXT_MUTED.hexval()[2:]}">[Risk: {risk}]</font>',
                        styles["small"],
                    )
                )

        # Remediation
        remediation = req.get("remediation", "")
        if remediation and status != "PASS":
            elements.append(Spacer(1, 3))
            elements.append(
                Paragraph(
                    f'<font color="#0369a1"><b>Recommendation:</b></font> {remediation}',
                    styles["small"],
                )
            )

        # GDPR cross-reference
        gdpr_articles = req.get("gdpr_articles", [])
        if gdpr_articles:
            elements.append(
                Paragraph(
                    f'<font color="#{TEXT_MUTED.hexval()[2:]}">GDPR: {", ".join(gdpr_articles)}</font>',
                    styles["small"],
                )
            )

        elements.append(Spacer(1, 8))
        elements.append(HRFlowable(width="100%", thickness=0.3, color=BORDER_COLOR))
        elements.append(Spacer(1, 6))

    # ── GDPR Assessment ────────────────────────────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("3. GDPR (EU 2016/679) Assessment", styles["section"]))

    gdpr_overall = gdpr.get("overall_status", "UNKNOWN")
    gdpr_hex = (
        f"#{_status_color(gdpr_overall).hexval()[2:]}"
        if hasattr(_status_color(gdpr_overall), "hexval")
        else "#333"
    )
    elements.append(
        Paragraph(
            f'Overall GDPR Status: <font color="{gdpr_hex}"><b>{_status_label(gdpr_overall)}</b></font>',
            styles["body"],
        )
    )
    elements.append(Spacer(1, 10))

    gdpr_checks = gdpr.get("checks", [])
    for check in gdpr_checks:
        status = check.get("status", "UNKNOWN")
        sc = _status_color(status)
        hex_s = f"#{sc.hexval()[2:]}" if hasattr(sc, "hexval") else "#333"

        elements.append(
            Paragraph(
                f"{check.get('article', '')} — "
                f"<b>{check.get('title', '')}</b> "
                f'<font color="{hex_s}">[{_status_label(status)}]</font>',
                styles["subsection"],
            )
        )

        evidence = check.get("evidence", "")
        if evidence:
            elements.append(Paragraph(evidence, styles["body"]))

        remediation = check.get("remediation")
        if remediation:
            elements.append(Spacer(1, 3))
            elements.append(
                Paragraph(
                    f'<font color="#0369a1"><b>Recommendation:</b></font> {remediation}',
                    styles["small"],
                )
            )

        elements.append(Spacer(1, 8))

    # ── OWASP → Regulation Cross-Reference ─────────────────────────────────
    elements.append(PageBreak())
    elements.append(
        Paragraph("4. OWASP → Regulation Cross-Reference", styles["section"])
    )
    elements.append(
        Paragraph(
            "Each OWASP API Security Top 10 (2023) category is mapped to "
            "applicable PCI DSS v4.0.1 requirements and GDPR articles.",
            styles["body"],
        )
    )
    elements.append(Spacer(1, 10))

    cross_ref_header = [
        Paragraph("<b>OWASP Category</b>", styles["table_header"]),
        Paragraph("<b>PCI DSS Requirements</b>", styles["table_header"]),
        Paragraph("<b>GDPR Articles</b>", styles["table_header"]),
    ]
    cross_ref_data = [cross_ref_header]

    from services.compliance_mapping import OWASP_PCI_DSS_MAPPING

    for owasp_id, mapping in OWASP_PCI_DSS_MAPPING.items():
        pci_ids = ", ".join(r["id"] for r in mapping["pci_requirements"])
        gdpr_arts = ", ".join(
            a.split(" — ")[0] for a in mapping.get("gdpr_articles", [])
        )
        cross_ref_data.append(
            [
                Paragraph(
                    f'<b>{owasp_id}</b><br/><font color="#{TEXT_MUTED.hexval()[2:]}">{mapping["owasp_name"]}</font>',
                    styles["table_cell"],
                ),
                Paragraph(pci_ids, styles["table_cell"]),
                Paragraph(gdpr_arts, styles["table_cell"]),
            ]
        )

    cross_ref_table = Table(cross_ref_data, colWidths=[150, 150, 160])
    cross_ref_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
                ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    elements.append(cross_ref_table)

    # ── Attestation ─────────────────────────────────────────────────────────
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("5. Attestation", styles["section"]))

    att = report_data.get("attestation", {})
    elements.append(
        Paragraph(
            f"<b>Tool:</b> {att.get('tool', '—')} v{att.get('version', '—')}",
            styles["body"],
        )
    )
    elements.append(
        Paragraph(
            f"<b>Scan Method:</b> {att.get('scan_method', '—')}",
            styles["body"],
        )
    )
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(att.get("note", ""), styles["body"]))

    elements.append(Spacer(1, 30))
    elements.append(HRFlowable(width="100%", thickness=1, color=BRAND_PRIMARY))
    elements.append(Spacer(1, 8))
    elements.append(
        Paragraph(
            f"Report generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            styles["small"],
        )
    )
    elements.append(
        Paragraph(
            "DevPulse API Security Scanner — Automated Compliance Evidence Generation",
            styles["small"],
        )
    )

    # Build PDF
    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()
