import * as vscode from "vscode";
import * as fs from "fs";
import { DevPulseClient } from "../services/devPulseClient";

export class CommandProvider {
  constructor(
    private devPulseClient: DevPulseClient,
    private context: vscode.ExtensionContext
  ) {}

  getQuickFixOptions(message: string): string[] {
    if (message.includes("CRITICAL")) {
      return [
        "Immediately disable endpoint",
        "Schedule security audit",
        "Review access logs",
        "Add security team to discussion"
      ];
    } else if (message.includes("HIGH")) {
      return [
        "Restrict access to authorized users",
        "Implement authentication",
        "Document endpoint",
        "Schedule investigation"
      ];
    } else if (message.includes("MEDIUM")) {
      return [
        "Review endpoint",
        "Verify authorization",
        "Add to API documentation",
        "Schedule assessment"
      ];
    }
    return ["Review endpoint", "Update documentation"];
  }

  async executeQuickFix(option: string, diagnostic: vscode.Diagnostic): Promise<void> {
    vscode.window.showInformationMessage(`Executing: ${option}`);
  }

  async generateReport(): Promise<string | null> {
    try {
      const metrics = await this.devPulseClient.getDashboardMetrics();
      const timestamp = new Date().toISOString().split('T')[0];
      const reportPath = `${this.context.globalStorageUri.fsPath}/devpulse-report-${timestamp}.md`;

      const content = `# DevPulse Security Report

Generated: ${new Date().toLocaleString()}

## Summary
- Total Endpoints: ${metrics.total_endpoints || 0}
- Shadow APIs: ${metrics.shadow_apis || 0}
- Security Alerts: ${metrics.security_alerts || 0}

## Risk Distribution
- Critical: ${metrics.critical_count || 0}
- High: ${metrics.high_count || 0}
- Medium: ${metrics.medium_count || 0}
- Low: ${metrics.low_count || 0}

## Compliance Status
- Requirements Met: ${metrics.compliance_met || 0}
- Violations: ${metrics.compliance_violations || 0}

---
*Report generated by DevPulse IDE Extension*
`;

      fs.writeFileSync(reportPath, content);
      return reportPath;
    } catch (error) {
      console.error("Error generating report:", error);
      return null;
    }
  }
}
