// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://sbtoqosnmpstkyumukzs.supabase.co';
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;
const RESOLVED_SUPABASE_URL = SUPABASE_URL || DEFAULT_SUPABASE_URL;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables!');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/** Global fetch with timeout for resilience against hanging requests */
const fetchWithTimeout = (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
  const timeoutMs = 30_000; // 30s max per request
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  return fetch(input, {
    ...init,
    signal: controller.signal,
  }).finally(() => clearTimeout(timeout));
};

export const supabase = createClient<Database>(
  RESOLVED_SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY || 'placeholder',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
    global: {
      headers: {
        'x-client-info': 'devpulse-agentguard',
      },
      fetch: fetchWithTimeout,
    },
  }
);

// Helper to check if Supabase is configured
export function isSupabaseConfigured(): boolean {
  return Boolean(RESOLVED_SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}