// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  "";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "";
const RESOLVED_SUPABASE_URL = SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/** Global fetch with timeout for resilience against hanging requests */
const fetchWithTimeout = (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
  // 10s timeout: fast failure detection without blocking UI
  const timeoutMs = 10_000;
  const controller = new AbortController();
  // Merge with existing signal if provided
  const existingSignal = (init as RequestInit & { signal?: AbortSignal })?.signal;
  if (existingSignal) {
    existingSignal.addEventListener("abort", () => controller.abort());
  }
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  return fetch(input, {
    ...init,
    signal: controller.signal,
  }).finally(() => clearTimeout(timeout));
};

export const supabase = createClient<Database>(
  RESOLVED_SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
    global: {
      headers: {
        'x-client-info': 'devpulse-agentguard',
      },
      fetch: fetchWithTimeout,
    },
  }
);

// Helper to check if Supabase is configured
export function isSupabaseConfigured(): boolean {
  const url = (RESOLVED_SUPABASE_URL || "").trim();
  const key = (SUPABASE_PUBLISHABLE_KEY || "").trim();
  if (!url || !key) return false;
  if (url.includes("placeholder") || key.includes("placeholder")) return false;
  if (url.includes("your-project.supabase.co") || key.includes("your-anon-publishable-key")) return false;
  return true;
}